python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_1.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_1
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_2.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_2
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_3.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_3
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_4.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_4
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_5.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_5
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_6.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_6
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_7.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_7
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_8.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_8
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_9.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_9
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_10.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_10
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_11.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_11
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_12.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_12
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_13.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_13
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_14.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_14
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_15.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_15
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_16.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_16
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_17.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_17
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_18.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_18
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_19.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_19
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_20.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_20
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_21.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_21
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_22.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_22
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_23.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_23
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_24.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_24
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_25.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_25
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_26.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_26
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_27.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_27
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_28.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_28
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_29.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_29
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_30.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_30
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_31.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_31
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_32.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_32
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_33.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_33
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_34.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_34
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_35.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_35
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_36.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_36
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_37.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_37
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_38.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_38
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_39.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_39
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_40.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_40
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_41.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_41
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_42.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_42
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_43.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_43
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_44.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_44
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_45.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_45
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_46.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_46
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_47.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_47
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_48.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_48
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_49.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_49
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_50.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_50
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_51.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_51
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_52.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_52
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_53.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_53
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_54.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_54
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_55.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_55
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_56.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_56
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_57.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_57
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_58.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_58
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_59.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_59
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_60.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_60
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_61.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_61
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_62.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_62
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_63.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_63
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_64.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_64
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_65.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_65
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_66.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_66
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_67.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_67
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_68.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_68
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_69.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_69
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_70.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_70
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_71.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_71
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_72.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_72
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_73.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_73
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_74.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_74
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_75.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_75
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_76.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_76
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_77.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_77
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_78.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_78
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_79.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_79
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_80.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_80
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_81.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_81
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_82.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_82
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_83.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_83
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_84.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_84
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_85.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_85
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_86.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_86
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_87.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_87
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_88.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_88
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_89.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_89
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_90.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_90
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_91.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_91
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_92.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_92
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_93.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_93
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_94.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_94
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_95.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_95
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_96.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_96
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_97.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_97
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_98.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_98
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_99.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_99
python BlockWise_BruteForce.py -f1 $1/Fusion_Approach_Pipelines/$2/Chiquet_100.csv -r $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_100