Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_1.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_1/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_2.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_2/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_3.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_3/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_4.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_4/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_5.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_5/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_6.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_6/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_7.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_7/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_8.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_8/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_9.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_9/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_10.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_10/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_11.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_11/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_12.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_12/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_13.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_13/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_14.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_14/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_15.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_15/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_16.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_16/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_17.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_17/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_18.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_18/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_19.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_19/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_20.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_20/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_21.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_21/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_22.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_22/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_23.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_23/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_24.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_24/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_25.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_25/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_26.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_26/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_27.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_27/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_28.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_28/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_29.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_29/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_30.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_30/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_31.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_31/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_32.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_32/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_33.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_33/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_34.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_34/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_35.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_35/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_36.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_36/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_37.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_37/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_38.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_38/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_39.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_39/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_40.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_40/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_41.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_41/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_42.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_42/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_43.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_43/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_44.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_44/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_45.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_45/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_46.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_46/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_47.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_47/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_48.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_48/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_49.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_49/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_50.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_50/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_51.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_51/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_52.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_52/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_53.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_53/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_54.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_54/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_55.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_55/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_56.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_56/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_57.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_57/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_58.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_58/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_59.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_59/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_60.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_60/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_61.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_61/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_62.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_62/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_63.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_63/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_64.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_64/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_65.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_65/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_66.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_66/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_67.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_67/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_68.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_68/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_69.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_69/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_70.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_70/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_71.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_71/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_72.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_72/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_73.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_73/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_74.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_74/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_75.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_75/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_76.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_76/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_77.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_77/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_78.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_78/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_79.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_79/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_80.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_80/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_81.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_81/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_82.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_82/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_83.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_83/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_84.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_84/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_85.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_85/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_86.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_86/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_87.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_87/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_88.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_88/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_89.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_89/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_90.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_90/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_91.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_91/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_92.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_92/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_93.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_93/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_94.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_94/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_95.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_95/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_96.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_96/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_97.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_97/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_98.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_98/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_99.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_99/
Rscript Implementation.R /u1/sua474/Dataset/Chiquet_For_Fusion_Approach/Chiquet_100.csv /u1/sua474/Fusion_Approach_Pipelines/Output/Spiec_Easi/Chiquet_100/