python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.1 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.2 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.3 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.4 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.5 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.6 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.7 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.8 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.9 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 1.0 -cor spearman -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.1 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.2 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.3 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.4 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.5 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.6 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.7 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.8 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.9 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 1.0 -cor spearman -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.1 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.2 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.3 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.4 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.5 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.6 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.7 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.8 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.9 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 1.0 -cor spearman -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.1 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.2 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.3 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.4 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.5 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.6 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.7 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.8 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.9 -cor spearman -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 1.0 -cor spearman -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.1 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.2 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.3 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.4 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.5 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.6 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.7 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.8 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.9 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 1.0 -cor pearson -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.1 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.2 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.3 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.4 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.5 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.6 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.7 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.8 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.9 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 1.0 -cor pearson -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.1 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.2 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.3 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.4 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.5 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.6 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.7 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.8 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.9 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 1.0 -cor pearson -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.1 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.2 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.3 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.4 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.5 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.6 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.7 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.8 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.9 -cor pearson -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 1.0 -cor pearson -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.1 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.2 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.3 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.4 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.5 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.6 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.7 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.8 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.9 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 1.0 -cor kendall -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.1 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.2 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.3 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.4 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.5 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.6 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.7 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.8 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.9 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 1.0 -cor kendall -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.1 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.2 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.3 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.4 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.5 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.6 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.7 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.8 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.9 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 1.0 -cor kendall -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.1 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.2 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.3 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.4 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.5 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.6 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.7 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.8 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.9 -cor kendall -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 1.0 -cor kendall -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.1 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.2 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.3 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.4 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.5 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.6 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.7 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.8 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 0.9 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent closeness -th 1.0 -cor MIC -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.1 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.2 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.3 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.4 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.5 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.6 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.7 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.8 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 0.9 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent eigenvector -th 1.0 -cor MIC -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.1 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.2 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.3 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.4 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.5 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.6 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.7 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.8 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 0.9 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent betweenness -th 1.0 -cor MIC -wt -cp both -pm -cg

python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.1 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.2 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.3 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.4 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.5 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.6 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.7 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.8 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 0.9 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 bromeA_all.csv -m log_transform -e kl_divergence -min 3 -c add_one -st 25 -si 25 -cent degree -th 1.0 -cor MIC -wt -cp both -pm -cg
