python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_1.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_1.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_1.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_2.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_2.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_2.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_3.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_3.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_3.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_4.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_4.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_4.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_5.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_5.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_5.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_6.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_6.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_6.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_7.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_7.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_7.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_8.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_8.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_8.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_9.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_9.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_9.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_10.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_10.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_10.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_11.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_11.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_11.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_12.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_12.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_12.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_13.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_13.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_13.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_14.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_14.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_14.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_15.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_15.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_15.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_16.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_16.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_16.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_17.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_17.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_17.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_18.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_18.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_18.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_19.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_19.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_19.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_20.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_20.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_20.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_21.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_21.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_21.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_22.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_22.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_22.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_23.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_23.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_23.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_24.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_24.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_24.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_25.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.10 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_25.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.15 -cor MIC -wt -cp both -pm -cg
python pipeline.py -f1 /u1/sua474/Data_files/Chiquet_Data/Chiquet_25.csv -m graph_centrality -e kl_divergence -min 0 -c add_one -st 'all' -si 'all' -cent degree -th 0.20 -cor MIC -wt -cp both -pm -cg
