Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_1.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_1/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_2.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_2/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_3.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_3/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_4.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_4/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_5.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_5/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_6.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_6/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_7.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_7/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_8.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_8/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_9.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_9/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_10.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_10/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_11.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_11/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_12.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_12/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_13.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_13/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_14.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_14/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_15.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_15/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_16.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_16/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_17.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_17/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_18.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_18/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_19.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_19/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_20.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_20/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_21.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_21/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_22.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_22/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_23.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_23/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_24.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_24/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_25.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_25/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_26.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_26/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_27.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_27/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_28.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_28/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_29.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_29/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_30.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_30/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_31.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_31/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_32.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_32/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_33.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_33/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_34.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_34/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_35.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_35/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_36.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_36/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_37.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_37/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_38.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_38/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_39.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_39/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_40.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_40/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_41.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_41/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_42.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_42/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_43.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_43/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_44.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_44/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_45.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_45/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_46.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_46/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_47.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_47/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_48.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_48/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_49.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_49/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_50.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_50/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_51.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_51/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_52.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_52/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_53.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_53/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_54.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_54/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_55.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_55/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_56.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_56/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_57.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_57/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_58.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_58/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_59.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_59/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_60.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_60/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_61.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_61/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_62.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_62/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_63.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_63/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_64.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_64/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_65.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_65/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_66.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_66/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_67.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_67/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_68.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_68/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_69.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_69/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_70.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_70/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_71.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_71/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_72.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_72/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_73.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_73/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_74.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_74/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_75.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_75/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_76.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_76/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_77.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_77/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_78.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_78/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_79.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_79/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_80.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_80/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_81.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_81/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_82.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_82/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_83.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_83/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_84.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_84/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_85.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_85/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_86.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_86/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_87.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_87/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_88.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_88/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_89.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_89/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_90.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_90/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_91.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_91/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_92.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_92/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_93.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_93/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_94.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_94/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_95.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_95/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_96.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_96/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_97.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_97/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_98.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_98/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_99.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_99/ $4
Rscript $1/Fusion_Approach_Pipelines/Pipelines/Spring/Implementation.R $1/Fusion_Approach_Pipelines/$2/Chiquet_100.csv $1/Fusion_Approach_Pipelines/Output/$3/Chiquet_100/ $4
